Fix compilation errors in bluetooth.cpp
Add missing variable declarations for speed sensor settings in the
connectedAndDiscovered() function:
- speed_as_bike: determines if speed sensor should be used as bike
- speedSensorName: configured speed sensor device name

These variables were referenced at line 2967 but were not declared
in scope, causing compilation errors.

Fixes:
- bluetooth.cpp:2967: error: 'speed_as_bike' was not declared in scope
- bluetooth.cpp:2969: error: 'speedSensorName' was not declared in scope